# sops configuration: creation rules for encrypting repository secrets
creation_rules:
  - # Rule: encrypt specific keys inside `secrets/secrets.yaml`
    path_regex: "secrets/secrets\\.yaml$"
    # Match specific top-level keys in the YAML to encrypt
    encrypted_regex: "^(admin-password-hash|restic-password|smb-credentials|technitium-admin-username|technitium-admin-password|qbittorrent-webui-username|qbittorrent-webui-password)$"
    # Age and SSH recipients for encryption. Folded for readability but preserved as a single value.
    age: >
      ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIATd/kn93HeAqaT5e8uW68n/JoWBesQkyruVNLsG3NDc khalid,
      age1aftkyfnfva6z3zvm725hj7rmqqpfw764hgsks2wzjne2mhdsdcwst398mf,
      age18waev2sm6xhla9wy0dy69v4zgs9m2sjt2p0qucclyjwryjdlq3ls8gx4dh,
      age142sglkrq86y2x33jupja456khepmfte6c3vf2j9edkas8y25z9fqj8640k,
      age1q3upcxvty6y8ly0m2yjjfaw00y64jcsulngt9a7v5fehap4u53xqug08w9,
      age15y5aa9dyf32rkf2trx506qtfvy4rca44f8jaw4tzypnutgme3g2qdystt0
